### ISSUE TITLE
xfce4-panel: white-on-white text on inactive tasks

### ISSUE THREAD

**Issue by Warudo** [B00merang-Project/Windows-10#163]
Using xfce4-panel 4.14.1 on Arch Linux, the text on inactive task buttons is white while their background color is also white. This makes it impossible to read the task name.

I jury rigged it with this in ~/.config/gtk-3.0/gtk.css:
```
.xfce4-panel.background .tasklist button:hover {
   background-image: none;
   background-color: #1a1a1a;
}
.xfce4-panel.background .tasklist button:checked {
   background-image: none;
   background-color: #1a1a1a;
}
.xfce4-panel.background .tasklist button {
   background-image: none;
   background-color: #000000; }
```
![xfce4-panel](https://user-images.githubusercontent.com/1916368/66228720-731f3a80-e6e0-11e9-9ef7-22e2b03e23a2.png)

**Comment by feren** [comment]
Just chiming in: Surely you should put 'transparent' as the color value rather than '#000' in there?

**Comment by Elbullazul** [comment]
can be fixed by modifying the xfce4-panel block. Will write the fix in master and push changes

**Comment by Elbullazul** [comment]
a72b81e3cfe96407b2fefee8b7ae67f2891c1db6 implements the new class and should fix it (haven't tried it)

**Comment by Warudo** [comment]
No, the issue is still present for me even with that commit.

**Comment by Elbullazul** [comment]
Weird, on manjaro latest it looks normal:

![VirtualBox_Manjaro 18 1 Xfce_08_10_2019_11_34_42](https://user-images.githubusercontent.com/15310985/66482892-f5f21d80-ea71-11e9-9c4b-0d4dba8b8a94.png)

Do you have the panel set to follow theme rules?

**Comment by Elbullazul** [comment]
Found the issue. 3334492 resolves it:

![VirtualBox_Manjaro 18 1 Xfce_09_10_2019_09_33_47](https://user-images.githubusercontent.com/15310985/66486064-ebd31d80-ea77-11e9-8fb4-ddac2a755392.png)

**Comment by Warudo** [comment]
Fix confirmed. Thanks!
